# Generated by Django 5.1.6 on 2025-02-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_app', '0002_student_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
    ]
