# Generated by Django 5.1.6 on 2025-02-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_app', '0003_stud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='Name',
            new_name='name',
        ),
    ]
