# Generated by Django 5.1.6 on 2025-02-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_app', '0004_rename_name_stud_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teacher_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Stud',
        ),
    ]
