# Generated by Django 5.1.6 on 2025-02-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_app', '0005_teacher_delete_stud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='marks',
            new_name='mark',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='MATHS', max_length=20),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='MATHS', max_length=20)),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_app.teacher')),
            ],
        ),
    ]
