# Generated by Django 5.1.6 on 2025-02-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_app', '0008_alter_busmodel_managers_busmodel_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='teacher_name',
            new_name='teacher_id',
        ),
    ]
